dist: xenial
language: go
go:
  - 1.13.1
go_import_path: github.com/cofyc/advanced-statefulset
services: docker
install: true
script:
  - make ${TARGET}
jobs:
  include:
  - env: TARGET=verify
  - env: TARGET=build
  - env: TARGET=test
  - env: TARGET=test-integration
  - env: TARGET=e2e
