kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
# Uncomment if you want more workers to test your workloads
- role: worker
# - role: worker
# - role: worker
# patch the generated kubeadm config with some extra settings
# CustomResourceDefaulting is avaiable in 1.16+.
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "CustomResourceDefaulting=true"
      "v": "4"
  scheduler:
    extraArgs:
      "feature-gates": "CustomResourceDefaulting=true"
      "v": "4"
  controllerManager:
    extraArgs:
      "feature-gates": "CustomResourceDefaulting=true"
      "v": "4"
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "CustomResourceDefaulting=true"
      "v": "4"
