kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
# Uncomment if you want more workers to test your workloads
- role: worker
# - role: worker
# - role: worker
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1alpha3
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "v": "4"
  scheduler:
    extraArgs:
      "v": "4"
  controllerManager:
    extraArgs:
      "v": "4"
- |
  apiVersion: kubeadm.k8s.io/v1alpha3
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      "v": "4"
