apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: advancedstatefulsets.pingcap.com
spec:
  group: pingcap.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: advancedstatefulsets
    singular: advancedstatefulset
    kind: AdvancedStatefulSet
  # TODO more validations, etc.
