apiVersion: apps.pingcap.com/v1alpha1
kind: StatefulSet
metadata:
  name: web
  annotations:
    deleted-slots: '[1]'
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
  revisionHistoryLimit: 10
